import { z } from "zod";
import { objectId, pagination } from "./common.js";
import { ORDER_STATUS, PAYMENT_MODES } from "../../lib/constants.js";

export const placeOrderSchema = z.object({
  // Generated by the browser once per checkout (UUID). Retrying with the same
  // key returns the order that was already created instead of a new one.
  idempotencyKey: z.string({ error: "Missing checkout key." }).regex(/^[A-Za-z0-9-]{16,64}$/, "Invalid checkout key."),
  addressId: objectId("delivery address").optional(),
  notes: z.string().trim().max(500, "Notes can be at most 500 characters.").default(""),
  // The total the shop saw on screen. NOT used for charging — only compared
  // with the server's total so the shop is told if prices changed meanwhile.
  expectedTotal: z.number().int().min(0).optional(),
});

const dateOnly = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

export const adminOrderListQuerySchema = z.object({
  status: z.enum(["all", "open", "closed", ...Object.values(ORDER_STATUS)]).catch("all"),
  q: z.string().trim().max(60).optional().catch(undefined),
  customerId: objectId().optional().catch(undefined),
  payment: z.enum(["unpaid", "partial", "paid", "overdue", "due"]).optional().catch(undefined),
  from: dateOnly.optional().catch(undefined),
  to: dateOnly.optional().catch(undefined),
  ...pagination,
});

export const confirmOrderSchema = z.object({
  quantities: z
    .array(
      z.object({
        itemId: objectId("item"),
        confirmedQty: z.number({ error: "Enter a quantity." }).int("Whole numbers only.").min(0, "Can't be negative."),
      }),
    )
    .max(200)
    .default([]),
  note: z.string().trim().max(500).default(""),
});

// CONFIRMED has its own endpoint (quantities + stock). Cancel/reject need a reason.
export const orderStatusSchema = z
  .object({
    status: z.enum([ORDER_STATUS.PACKED, ORDER_STATUS.DISPATCHED, ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REJECTED], {
      error: "Choose a valid status.",
    }),
    note: z.string().trim().max(500).default(""),
  })
  .refine((d) => ![ORDER_STATUS.CANCELLED, ORDER_STATUS.REJECTED].includes(d.status) || d.note.length >= 3, {
    path: ["note"],
    message: "Please give a reason — the shop will see it.",
  });

const dateOnlyStr = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use a valid date.");

export const recordPaymentSchema = z.object({
  amount: z.number({ error: "Enter the amount received." }).int("Enter a valid amount.").min(1, "Amount must be more than ₹0."),
  mode: z.enum(Object.keys(PAYMENT_MODES), { error: "Choose how it was paid." }),
  paidOn: z.union([z.literal(""), dateOnlyStr]).optional(),
  reference: z.string().trim().max(100).default(""),
  note: z.string().trim().max(300).default(""),
});

export const voidPaymentSchema = z.object({
  reason: z.string({ error: "Give a reason." }).trim().min(3, "Give a reason (e.g. entered twice, cheque bounced).").max(300),
});

export const shopCancelSchema = z.object({
  reason: z.string().trim().max(300).default(""),
});

export const orderListQuerySchema = z.object({
  ...pagination,
  limit: z.coerce.number().int().min(1).max(50).catch(20),
});

const orderLines = z
  .array(
    z.object({
      productId: objectId("product"),
      quantity: z.number({ error: "Enter a quantity." }).int("Whole numbers only.").min(1, "At least 1.").max(100_000),
    }),
  )
  .max(200, "An order can have up to 200 products.");

export const adminOrderPreviewSchema = z.object({
  customerId: objectId("shop"),
  items: orderLines.default([]),
});

export const adminOrderCreateSchema = z.object({
  customerId: objectId("shop"),
  items: orderLines.min(1, "Add at least one product."),
  addressId: objectId("delivery address").optional(),
  notes: z.string().trim().max(500).default(""),
  idempotencyKey: z.string().regex(/^[A-Za-z0-9-]{16,64}$/, "Invalid key."),
  expectedTotal: z.number().int().min(0).optional(),
  confirmNow: z.boolean().default(false),
});
