import { z } from "zod";
import { objectId, pagination } from "./common.js";

export const placeOrderSchema = z.object({
  // Generated by the browser once per checkout (UUID). Retrying with the same
  // key returns the order that was already created instead of a new one.
  idempotencyKey: z.string({ error: "Missing checkout key." }).regex(/^[A-Za-z0-9-]{16,64}$/, "Invalid checkout key."),
  addressId: objectId("delivery address").optional(),
  notes: z.string().trim().max(500, "Notes can be at most 500 characters.").default(""),
  // The total the shop saw on screen. NOT used for charging — only compared
  // with the server's total so the shop is told if prices changed meanwhile.
  expectedTotal: z.number().int().min(0).optional(),
});

export const orderListQuerySchema = z.object({
  ...pagination,
  limit: z.coerce.number().int().min(1).max(50).catch(20),
});
