"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Textarea from "@/components/ui/Textarea";
import Checkbox from "@/components/ui/Checkbox";
import Card from "@/components/ui/Card";
import Alert from "@/components/ui/Alert";
import AddressFields, { EMPTY_ADDRESS } from "./AddressFields";
import PasswordSetter from "./PasswordSetter";
import LoginDetailsBox from "./LoginDetailsBox";
import { api } from "@/lib/apiClient";
import { toPaise, fromPaise } from "@/lib/money";
import { generatePassword } from "@/lib/generatePassword";

const sameAddress = (a, b) => Object.keys(EMPTY_ADDRESS).every((k) => (a?.[k] ?? "") === (b?.[k] ?? ""));

function initialState(customer, password = "") {
  const billing = { ...EMPTY_ADDRESS, ...customer?.billingAddress };
  const shipping = { ...EMPTY_ADDRESS, ...customer?.shippingAddress };
  return {
    shopName: customer?.shopName ?? "",
    ownerName: customer?.ownerName ?? "",
    phone: customer?.phone ?? "",
    email: customer?.email ?? "",
    gstin: customer?.gstin ?? "",
    customerCode: customer?.customerCode ?? "",
    billingAddress: billing,
    shippingAddress: shipping,
    shippingSame: customer ? sameAddress(billing, shipping) : true,
    creditLimit: customer?.creditLimit ? String(fromPaise(customer.creditLimit)) : "",
    paymentTerms: customer?.paymentTerms ?? "",
    notes: customer?.notes ?? "",
    password,
  };
}

// initialPassword is generated by the server page, so the server-rendered HTML
// and the browser's first render show the same value.
export default function CustomerForm({ customer, initialPassword = "" }) {
  const router = useRouter();
  const isNew = !customer;
  const [form, setForm] = useState(() => initialState(customer, initialPassword));
  const [errors, setErrors] = useState({});
  const [formError, setFormError] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [createdCustomer, setCreatedCustomer] = useState(null);

  const update = (patch) => {
    setForm((f) => ({ ...f, ...patch }));
    setSaved(false);
  };
  const set = (field) => (e) => update({ [field]: e.target.type === "checkbox" ? e.target.checked : e.target.value });

  async function onSubmit(e) {
    e.preventDefault();
    if (saving) return;
    setSaving(true);
    setErrors({});
    setFormError(null);

    const body = {
      shopName: form.shopName,
      ownerName: form.ownerName,
      phone: form.phone,
      email: form.email.trim(),
      gstin: form.gstin.trim(),
      customerCode: form.customerCode.trim(),
      billingAddress: form.billingAddress,
      shippingAddress: form.shippingSame ? form.billingAddress : form.shippingAddress,
      creditLimit: form.creditLimit.trim() ? toPaise(form.creditLimit) : 0,
      paymentTerms: form.paymentTerms,
      notes: form.notes,
      ...(isNew && { password: form.password }),
    };

    const res = isNew ? await api.post("/api/admin/customers", body) : await api.patch(`/api/admin/customers/${customer.id}`, body);
    setSaving(false);

    if (!res.ok) {
      setErrors(res.error.fields ?? {});
      setFormError(res.error.message);
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }

    if (isNew) {
      setCreatedCustomer({ ...res.data, password: form.password });
      window.scrollTo({ top: 0, behavior: "smooth" });
    } else {
      setSaved(true);
      router.refresh();
    }
  }

  if (createdCustomer) {
    return (
      <Card className="space-y-4 p-5">
        <Alert tone="success">
          {createdCustomer.shopName} was added as customer {createdCustomer.customerCode}.
        </Alert>
        <LoginDetailsBox shopName={createdCustomer.shopName} phone={createdCustomer.phone} password={createdCustomer.password} />
        <div className="flex flex-wrap gap-3">
          <Button href={`/admin/customers/${createdCustomer.id}/pricing`}>Set special prices</Button>
          <Button variant="secondary" href={`/admin/customers/${createdCustomer.id}`}>Open customer</Button>
          <Button variant="ghost" onClick={() => { setCreatedCustomer(null); setForm(initialState(null, generatePassword())); }}>Add another</Button>
        </div>
      </Card>
    );
  }

  return (
    <form onSubmit={onSubmit} noValidate className="space-y-6">
      {formError && <Alert tone="error">{formError}</Alert>}
      {saved && <Alert tone="success">Changes saved.</Alert>}

      <Card className="space-y-4 p-5">
        <h2 className="font-semibold">Shop details</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <Input className="sm:col-span-2" label="Shop name *" value={form.shopName} onChange={set("shopName")} error={errors.shopName} maxLength={120} placeholder="e.g. Sharma General Store" />
          <Input label="Owner name" value={form.ownerName} onChange={set("ownerName")} error={errors.ownerName} maxLength={100} />
          <Input
            label="Mobile number *"
            type="tel"
            inputMode="numeric"
            value={form.phone}
            onChange={set("phone")}
            error={errors.phone}
            hint={isNew ? "The shopkeeper logs in with this number." : "Changing it also changes the login number."}
          />
          <Input label="Email" type="email" value={form.email} onChange={set("email")} error={errors.email} />
          <Input label="GSTIN" value={form.gstin} onChange={set("gstin")} error={errors.gstin} maxLength={15} autoCapitalize="characters" />
          <Input
            label="Customer code"
            value={form.customerCode}
            onChange={set("customerCode")}
            error={errors.customerCode}
            maxLength={30}
            placeholder={isNew ? "Auto (C0001…)" : ""}
            hint={isNew ? "Leave empty to generate one." : undefined}
          />
        </div>
      </Card>

      <Card className="space-y-4 p-5">
        <h2 className="font-semibold">Billing address</h2>
        <AddressFields prefix="billingAddress" value={form.billingAddress} onChange={(v) => update({ billingAddress: v })} errors={errors} />
      </Card>

      <Card className="space-y-4 p-5">
        <h2 className="font-semibold">Delivery address</h2>
        <Checkbox label="Same as billing address" checked={form.shippingSame} onChange={set("shippingSame")} />
        {!form.shippingSame && (
          <AddressFields prefix="shippingAddress" value={form.shippingAddress} onChange={(v) => update({ shippingAddress: v })} errors={errors} />
        )}
      </Card>

      <Card className="space-y-4 p-5">
        <h2 className="font-semibold">Credit &amp; terms</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <Input label="Credit limit (₹)" inputMode="decimal" value={form.creditLimit} onChange={set("creditLimit")} error={errors.creditLimit} hint="For reference only in this version." />
          <Input label="Payment terms" value={form.paymentTerms} onChange={set("paymentTerms")} error={errors.paymentTerms} maxLength={60} placeholder="e.g. 15 days credit" />
        </div>
        <Textarea label="Internal notes" value={form.notes} onChange={set("notes")} error={errors.notes} maxLength={1000} hint="Only visible to your team." />
      </Card>

      {isNew && (
        <Card className="space-y-4 p-5">
          <h2 className="font-semibold">Login</h2>
          <PasswordSetter value={form.password} onChange={(password) => update({ password })} error={errors.password} />
        </Card>
      )}

      <div className="flex gap-3">
        <Button type="submit" size="lg" loading={saving}>{isNew ? "Create customer" : "Save changes"}</Button>
        <Button variant="secondary" size="lg" href="/admin/customers">{isNew ? "Cancel" : "Back"}</Button>
      </div>
    </form>
  );
}
